package cn.hamgol.entity.core.auth;

import java.io.Serializable;
import java.util.Date;

public class SysOrgRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_sys_org_role.or_oid
     *
     * @mbg.generated
     */
    private String orOid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_sys_org_role.or_rid
     *
     * @mbg.generated
     */
    private String orRid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_sys_org_role.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_sys_org_role.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_sys_org_role.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_sys_org_role.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auth_sys_org_role
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_sys_org_role.or_oid
     *
     * @return the value of auth_sys_org_role.or_oid
     *
     * @mbg.generated
     */
    public String getOrOid() {
        return orOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_sys_org_role.or_oid
     *
     * @param orOid the value for auth_sys_org_role.or_oid
     *
     * @mbg.generated
     */
    public void setOrOid(String orOid) {
        this.orOid = orOid == null ? null : orOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_sys_org_role.or_rid
     *
     * @return the value of auth_sys_org_role.or_rid
     *
     * @mbg.generated
     */
    public String getOrRid() {
        return orRid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_sys_org_role.or_rid
     *
     * @param orRid the value for auth_sys_org_role.or_rid
     *
     * @mbg.generated
     */
    public void setOrRid(String orRid) {
        this.orRid = orRid == null ? null : orRid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_sys_org_role.create_time
     *
     * @return the value of auth_sys_org_role.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_sys_org_role.create_time
     *
     * @param createTime the value for auth_sys_org_role.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_sys_org_role.create_user
     *
     * @return the value of auth_sys_org_role.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_sys_org_role.create_user
     *
     * @param createUser the value for auth_sys_org_role.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_sys_org_role.update_time
     *
     * @return the value of auth_sys_org_role.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_sys_org_role.update_time
     *
     * @param updateTime the value for auth_sys_org_role.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_sys_org_role.update_user
     *
     * @return the value of auth_sys_org_role.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_sys_org_role.update_user
     *
     * @param updateUser the value for auth_sys_org_role.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_org_role
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysOrgRole other = (SysOrgRole) that;
        return (this.getOrOid() == null ? other.getOrOid() == null : this.getOrOid().equals(other.getOrOid()))
            && (this.getOrRid() == null ? other.getOrRid() == null : this.getOrRid().equals(other.getOrRid()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateUser() == null ? other.getCreateUser() == null : this.getCreateUser().equals(other.getCreateUser()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateUser() == null ? other.getUpdateUser() == null : this.getUpdateUser().equals(other.getUpdateUser()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_org_role
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrOid() == null) ? 0 : getOrOid().hashCode());
        result = prime * result + ((getOrRid() == null) ? 0 : getOrRid().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateUser() == null) ? 0 : getCreateUser().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateUser() == null) ? 0 : getUpdateUser().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_org_role
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orOid=").append(orOid);
        sb.append(", orRid=").append(orRid);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}