package cn.hamgol.dao.auth;

import cn.hamgol.entity.auth.SysRole;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role
     *
     * @mbg.generated
     */
    @Delete({
        "delete from auth_sys_role",
        "where role_id = #{roleId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role
     *
     * @mbg.generated
     */
    @Insert({
        "insert into auth_sys_role (role_id, role_name)",
        "values (#{roleId,jdbcType=VARCHAR}, #{roleName,jdbcType=VARCHAR})"
    })
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role
     *
     * @mbg.generated
     */
    int insertSelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "role_id, role_name",
        "from auth_sys_role",
        "where role_id = #{roleId,jdbcType=VARCHAR}"
    })
    @ResultMap("cn.hamgol.dao.auth.SysRoleMapper.BaseResultMap")
    SysRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role
     *
     * @mbg.generated
     */
    @Update({
        "update auth_sys_role",
        "set role_name = #{roleName,jdbcType=VARCHAR}",
        "where role_id = #{roleId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysRole record);
}