package cn.hamgol.dao.db.test;

import cn.hamgol.entity.db.test.TestModule;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TestModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbg.generated
     */
    @Delete({
        "delete from test_module",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbg.generated
     */
    @Insert({
        "insert into test_module (id, title, ",
        "create_time, create_id, ",
        "update_time, update_id)",
        "values (#{id,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createId,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{updateId,jdbcType=VARCHAR})"
    })
    int insert(TestModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbg.generated
     */
    int insertSelective(TestModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, title, create_time, create_id, update_time, update_id",
        "from test_module",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("cn.hamgol.dao.db.test.TestModuleMapper.BaseResultMap")
    TestModule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TestModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_module
     *
     * @mbg.generated
     */
    @Update({
        "update test_module",
        "set title = #{title,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_id = #{createId,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_id = #{updateId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(TestModule record);
}