package cn.hamgol.dao.core.auth;

import cn.hamgol.entity.core.auth.SysCorpRole;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SysCorpRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_corp_role
     *
     * @mbg.generated
     */
    @Delete({
        "delete from auth_sys_corp_role",
        "where cr_cid = #{crCid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String crCid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_corp_role
     *
     * @mbg.generated
     */
    @Insert({
        "insert into auth_sys_corp_role (cr_cid, cr_rid, ",
        "create_time, create_user, ",
        "update_time, update_user)",
        "values (#{crCid,jdbcType=VARCHAR}, #{crRid,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createUser,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{updateUser,jdbcType=VARCHAR})"
    })
    int insert(SysCorpRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_corp_role
     *
     * @mbg.generated
     */
    int insertSelective(SysCorpRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_corp_role
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "cr_cid, cr_rid, create_time, create_user, update_time, update_user",
        "from auth_sys_corp_role",
        "where cr_cid = #{crCid,jdbcType=VARCHAR}"
    })
    @ResultMap("cn.hamgol.dao.core.auth.SysCorpRoleMapper.BaseResultMap")
    SysCorpRole selectByPrimaryKey(String crCid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_corp_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysCorpRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_corp_role
     *
     * @mbg.generated
     */
    @Update({
        "update auth_sys_corp_role",
        "set cr_rid = #{crRid,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_user = #{createUser,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_user = #{updateUser,jdbcType=VARCHAR}",
        "where cr_cid = #{crCid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysCorpRole record);
}