package cn.hamgol.dao.core.auth;

import cn.hamgol.entity.core.auth.SysOrgRole;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SysOrgRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_org_role
     *
     * @mbg.generated
     */
    @Delete({
        "delete from auth_sys_org_role",
        "where or_oid = #{orOid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String orOid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_org_role
     *
     * @mbg.generated
     */
    @Insert({
        "insert into auth_sys_org_role (or_oid, or_rid, ",
        "create_time, create_user, ",
        "update_time, update_user)",
        "values (#{orOid,jdbcType=VARCHAR}, #{orRid,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createUser,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{updateUser,jdbcType=VARCHAR})"
    })
    int insert(SysOrgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_org_role
     *
     * @mbg.generated
     */
    int insertSelective(SysOrgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_org_role
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "or_oid, or_rid, create_time, create_user, update_time, update_user",
        "from auth_sys_org_role",
        "where or_oid = #{orOid,jdbcType=VARCHAR}"
    })
    @ResultMap("cn.hamgol.dao.core.auth.SysOrgRoleMapper.BaseResultMap")
    SysOrgRole selectByPrimaryKey(String orOid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_org_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysOrgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_org_role
     *
     * @mbg.generated
     */
    @Update({
        "update auth_sys_org_role",
        "set or_rid = #{orRid,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_user = #{createUser,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_user = #{updateUser,jdbcType=VARCHAR}",
        "where or_oid = #{orOid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysOrgRole record);
}