package cn.hamgol.dao.core.auth;

import cn.hamgol.entity.core.auth.SysOrg;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SysOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_org
     *
     * @mbg.generated
     */
    @Delete({
        "delete from auth_sys_org",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_org
     *
     * @mbg.generated
     */
    @Insert({
        "insert into auth_sys_org (id, title, ",
        "pid, create_time, ",
        "create_user, update_time, ",
        "update_user)",
        "values (#{id,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, ",
        "#{pid,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{createUser,jdbcType=VARCHAR}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{updateUser,jdbcType=VARCHAR})"
    })
    int insert(SysOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_org
     *
     * @mbg.generated
     */
    int insertSelective(SysOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_org
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, title, pid, create_time, create_user, update_time, update_user",
        "from auth_sys_org",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("cn.hamgol.dao.core.auth.SysOrgMapper.BaseResultMap")
    SysOrg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_org
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_org
     *
     * @mbg.generated
     */
    @Update({
        "update auth_sys_org",
        "set title = #{title,jdbcType=VARCHAR},",
          "pid = #{pid,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_user = #{createUser,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_user = #{updateUser,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysOrg record);
}