package cn.hamgol.dao.core.auth;

import cn.hamgol.entity.core.auth.SysRolePerm;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SysRolePermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role_perm
     *
     * @mbg.generated
     */
    @Delete({
        "delete from auth_sys_role_perm",
        "where rp_rid = #{rpRid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String rpRid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role_perm
     *
     * @mbg.generated
     */
    @Insert({
        "insert into auth_sys_role_perm (rp_rid, rp_pid, ",
        "create_time, create_user, ",
        "update_time, update_user)",
        "values (#{rpRid,jdbcType=VARCHAR}, #{rpPid,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createUser,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{updateUser,jdbcType=VARCHAR})"
    })
    int insert(SysRolePerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role_perm
     *
     * @mbg.generated
     */
    int insertSelective(SysRolePerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role_perm
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "rp_rid, rp_pid, create_time, create_user, update_time, update_user",
        "from auth_sys_role_perm",
        "where rp_rid = #{rpRid,jdbcType=VARCHAR}"
    })
    @ResultMap("cn.hamgol.dao.core.auth.SysRolePermMapper.BaseResultMap")
    SysRolePerm selectByPrimaryKey(String rpRid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role_perm
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysRolePerm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role_perm
     *
     * @mbg.generated
     */
    @Update({
        "update auth_sys_role_perm",
        "set rp_pid = #{rpPid,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_user = #{createUser,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_user = #{updateUser,jdbcType=VARCHAR}",
        "where rp_rid = #{rpRid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysRolePerm record);
}