package cn.hamgol.dao.core.auth;

import cn.hamgol.entity.core.auth.SysRoleUser;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SysRoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role_user
     *
     * @mbg.generated
     */
    @Delete({
        "delete from auth_sys_role_user",
        "where ur_uid = #{urUid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String urUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role_user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into auth_sys_role_user (ur_uid, ur_rid, ",
        "create_time, create_user, ",
        "update_time, update_user)",
        "values (#{urUid,jdbcType=VARCHAR}, #{urRid,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createUser,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{updateUser,jdbcType=VARCHAR})"
    })
    int insert(SysRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role_user
     *
     * @mbg.generated
     */
    int insertSelective(SysRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role_user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "ur_uid, ur_rid, create_time, create_user, update_time, update_user",
        "from auth_sys_role_user",
        "where ur_uid = #{urUid,jdbcType=VARCHAR}"
    })
    @ResultMap("cn.hamgol.dao.core.auth.SysRoleUserMapper.BaseResultMap")
    SysRoleUser selectByPrimaryKey(String urUid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_role_user
     *
     * @mbg.generated
     */
    @Update({
        "update auth_sys_role_user",
        "set ur_rid = #{urRid,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_user = #{createUser,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_user = #{updateUser,jdbcType=VARCHAR}",
        "where ur_uid = #{urUid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysRoleUser record);
}