package cn.hamgol.dao.core.auth;

import cn.hamgol.entity.core.auth.SysUserInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SysUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_user_info
     *
     * @mbg.generated
     */
    @Delete({
        "delete from auth_sys_user_info",
        "where uid = #{uid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_user_info
     *
     * @mbg.generated
     */
    @Insert({
        "insert into auth_sys_user_info (uid, create_time, ",
        "create_user, update_time, ",
        "update_user)",
        "values (#{uid,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{createUser,jdbcType=VARCHAR}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{updateUser,jdbcType=VARCHAR})"
    })
    int insert(SysUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_user_info
     *
     * @mbg.generated
     */
    int insertSelective(SysUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_user_info
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "uid, create_time, create_user, update_time, update_user",
        "from auth_sys_user_info",
        "where uid = #{uid,jdbcType=VARCHAR}"
    })
    @ResultMap("cn.hamgol.dao.core.auth.SysUserInfoMapper.BaseResultMap")
    SysUserInfo selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_sys_user_info
     *
     * @mbg.generated
     */
    @Update({
        "update auth_sys_user_info",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_user = #{createUser,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_user = #{updateUser,jdbcType=VARCHAR}",
        "where uid = #{uid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(SysUserInfo record);
}